### ISSUE TITLE
Implement/import a POS tagger

### ISSUE THREAD

**Issue by yehosef** [angeloskath/php-nlp-tools#26]
There is a different project at https://github.com/angeloskath/pos-tag but it seems it should be integrated and part of the entire toolkit.

**Comment by angeloskath** [comment]
Hey @kinow, useless 2 year late response I know but better 2 years late than never.

Firstly, thank you very much for offering. When you sent that I probably needed some help because 2 years later still nothing has been done.

Anyway, just had to say thank you before closing the issue.
