### ISSUE TITLE
error while much array

### ISSUE THREAD

**Issue by MisterFredy** [angeloskath/php-nlp-tools#53]
im sorry my english is bad.but i found error while i give more array input to hierarchi cluster
      ```
  $clusters = range(0,count($documents)-1);
        $c = count($clusters);
        while ($c>1) {
            // ask the strategy which to merge. The strategy
            // will assume that we will indeed merge the returned clusters
            list($i,$j) = $this->strategy->getNextMerge();
            $clusters[$i] = array($clusters[$i],$clusters[$j]);
            unset($clusters[$j]);
            $c--;
        }
        $clusters = array($clusters[$i]);
```
my error stack is Undefined variable: i maybe you can fix this :)

**Comment by angeloskath** [comment]
Judging from your snippet you are using the MergeStrategyInterface directly. I would suggest you use the [Hierarchical](http://php-nlp-tools.com/documentation/api/#NlpTools/Clustering/Hierarchical) clusterer. You can also find a small example in the [docs](http://php-nlp-tools.com/documentation/clustering.html).

If you want more specific help please add a runnable code snippet to reproduce the error.

Thanks,
Angelos
