### ISSUE TITLE
Find most similar

### ISSUE THREAD

**Issue by it-is-hacker-time** [angeloskath/php-nlp-tools#63]
What algoritm should I use to find the closest match from a string to a set of strings.

Example of known inputs:
```
I would like a cheese pizza
I would like a cheese pizza with onions
I would like a cheese pizza without onions
```

Input I wanna match up and find most similiar, in case there are any similar (in this example there are just spelling mistakes):
```
I would like a ceese pizza with out onnions.
```

**Comment by angeloskath** [comment]
There are several [similarities](http://php-nlp-tools.com/documentation/similarity.html) implemented in the library. The main idea would be to compute features for the strings and then the similarity should be computed based on the features.

If you want to try some experimental feature in the [develop](https://github.com/angeloskath/php-nlp-tools/tree/develop) branch there is a [KDTree](https://github.com/angeloskath/php-nlp-tools/blob/develop/src/NlpTools/Similarity/Neighbors/KDTree.php) implemented which can return the k-nearest neighbors in a set of documents.
